### ISSUE TITLE
Empty enums in a FAST template are not propagated to UI schema

### ISSUE THREAD

**Issue by JoeBenner** [f5devcentral/f5-fast-core#28]
we have a use case where we generate a form from FAST generated UI schema but before we do we insert an enum into the template. Quite a bit like enumFromBigip. This enum can be empty, which means there is nothing to choose. The template can't be used but this is a viable situation.

The trouble is, when there is an empty enum in the template, fast core just drops it when it generates the UI schema and the field becomes a string input field. There is no possible valid value that can be entered. What we need is an empty list.

Here is a very simplified example but it makes the point...
**Non-empty enum works as expected**
This template:  
```
definitions:
  certificatesEnum:
    title: Please choose a certificate
    type: string
    enum: [cert1, cert2]
template: |
     "bigip": "{{certificatesEnum}}.crt"
```   
Produces this schema (this is good - it produces a list):  
```
{
    "definitions": {},
    "description": "",
    "properties": {
      "certificatesEnum": {
        "enum": [
          "cert1",
          "cert2"
        ],
        "title": "Please choose a certificate",
        "type": "string"
      }
    },
    "required": [
      "certificatesEnum"
    ],
    "title": "",
    "type": "object"
  }
```  
**Empty enum is dropped from schema**
This template (same template with empty enum):  
```
definitions:
  certificatesEnum:
    title: Please choose a certificate
    type: string
    enum: []
template: |
     "bigip": "{{certificatesEnum}}.crt"
```
Produces this schema (certificatesEnum is a string input field (and title is gone):  
```
{
    "definitions": {},
    "description": "",
    "properties": {
      "certificatesEnum": {
        "type": "string"
      }
    },
    "required": [
      "certificatesEnum"
    ],
    "title": "",
    "type": "object"
  }
```
**Expected - empty enum in schema (and title still there)**
```
{
    "definitions": {},
    "description": "",
    "properties": {
      "certificatesEnum": {
        "enum": [],
        "title": "Please choose a certificate",
        "type": "string"
      }
    },
    "required": [
      "certificatesEnum"
    ],
    "title": "",
    "type": "object"
  }
```
